---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: '您可以通过BlueXP数字电子钱包管理和监控从NetApp购买的BlueXP许可证(BYOL)、BlueXP Marketplace订阅和NetApp Keystone。' 
---
= 了解有关BlueXP数字市场的信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
通过BlueXP  数字钱包、您可以管理和监控从NetApp (BYOL)、BlueXP  数据服务市场订阅(包括NetApp Cloud Volumes ONTAP)和NetApp Keystone购买的BlueXP  许可证。



== 如何在电子钱包中显示许可证和订阅

如果用于订阅的BlueXP  帐户同时也是NetApp支持站点帐户、则许可证和订阅都会自动显示在数字钱包中。如果您使用的BlueXP  帐户未与您的NetApp支持站点(NSS)帐户关联、则需要手动添加和更新许可证、并且不会看到使用情况、容量和其他详细信息发生更改。


NOTE: 您需要部署Connector才能查看数字钱包中的订阅信息。要查看Cloud Volumes ONTAP的节点许可证、还需要使用连接器。

同时、BlueXP会自动查询NetApp的许可服务、以获取与您的NetApp 支持站点 帐户关联的许可证的详细信息。如果没有错误、BlueXP会自动将许可证添加到电子钱包中。

如果BlueXP  无法添加许可证、您需要手动将其添加到电子钱包中。例如、如果您的BlueXP  用户帐户未与您的NetApp支持站点帐户关联、则您需要自行添加许可证。

从NetApp销售代表处购买许可证后、NetApp会向您发送一封电子邮件、其中包含序列号和其他许可详细信息。您需要该序列号才能在数字钱包中添加或更新相应的许可证。

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["了解如何将NetApp支持站点帐户添加到BlueXP  用户凭据中"^](英文)



== 支持的服务

您可以通过BlueXP  数字钱包管理以下服务的许可证和订阅：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["备份和恢复"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["灾难恢复"^] (仅限BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["勒索软件保护"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["内部 ONTAP 集群"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["分层"^]

